#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "trying to serve docs"
cd /app/docs && pwd
cd /app/docs && make livehtml

python manage.py migrate
python manage.py runserver_plus 0.0.0.0:8000